name: Python CI

# Se dispara al hacer push a las ramas develop y main
on:
  push:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies
      - run: pip install -r requirements.txt
      - name: Run unit tests
      - run: pytest tests/unit
      - name: Run integration tests
      - run: pytest tests/integration
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: > 
            -Dsonar.projectKey=trivia-game-python 
            -Dsonar.sources=.